name: dlp3-keras3-gpu
channels:
  - conda-forge
  - pytorch  # PyTorch channel for better compatibility
  - nvidia  # NVIDIA channel for CUDA packages
  - defaults
dependencies:
  - python=3.11  # Python 3.11 for better compatibility
  - pip  # Python's package-management system
  - jupyterlab=4.0  # Latest JupyterLab for better experience
  - jupyter=1.0  # Jupyter notebook support
  - ipython=8.18  # Interactive Python shell
  - ipywidgets=8.1  # Jupyter widgets
  - matplotlib=3.8  # Plotting library
  - numpy=1.26  # Numerical computing
  - pandas=2.1  # Data manipulation and analysis
  - pillow=10.0  # Image processing library
  - scikit-learn=1.3  # Machine learning library
  - scipy=1.11  # Scientific computing library
  - requests=2.31  # HTTP library
  - tqdm=4.66  # Progress bars
  - seaborn=0.13  # Statistical data visualization
  - graphviz  # Graph visualization
  - python-graphviz  # Python interface for Graphviz
  - pydot=1.4  # Interface to Graphviz
  # PyTorch from conda (better CUDA compatibility)
  - pytorch>=2.1.0  # PyTorch from conda channel
  - torchvision  # PyTorch vision utilities
  - pytorch-cuda=12.1  # CUDA support for PyTorch
  - pip:
    # Keras 3 and backend support
    - keras==3.11.3  # Keras 3 - latest stable version
    - tensorflow==2.17.1  # TensorFlow (CPU version to avoid CUDA conflicts)
    - tf-keras==2.17.0  # TensorFlow-specific Keras components
    - keras-hub==0.21.1  # Keras Hub for pre-trained models
    # JAX with CPU version (can be upgraded later if needed)
    - jax[cpu]>=0.4.20  # JAX backend option
    - kagglehub>=0.3.0  # Kaggle dataset access
    - tensorflow-datasets>=4.9.0  # TensorFlow datasets
    - tensorflow-hub>=0.16.0  # TensorFlow Hub for pre-trained models
    - transformers>=4.30.0  # Hugging Face transformers
    - tokenizers>=0.13.0  # Fast tokenizers for transformers
    - datasets>=2.14.0  # Hugging Face datasets
    - accelerate>=0.20.0  # Hugging Face acceleration library
    - gradio>=4.0.0  # Optional: for building quick ML demos
    - wandb>=0.16.0  # Optional: experiment tracking
