name: dlp3-pytorch
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab=4.0
  - jupyter=1.0
  - ipython=8.18
  - ipywidgets=8.1
  - matplotlib=3.8
  - numpy=1.26
  - pandas=2.1
  - pillow=10.0
  - scikit-learn=1.3
  - scipy=1.11
  - requests=2.31
  - tqdm=4.66
  - seaborn=0.13
  - graphviz
  - python-graphviz
  - pydot=1.4
  # PyTorch ecosystem from conda
  - pytorch>=2.1.0
  - torchvision
  - pytorch-cuda=12.1
  - pip:
    # Keras 3 with PyTorch backend
    - keras==3.11.3
    - keras-hub==0.21.1
    # Additional packages
    - kagglehub>=0.3.0
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - datasets>=2.14.0
    - accelerate>=0.20.0
