name: dlp3-tf-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab=4.0
  - jupyter=1.0
  - ipython=8.18
  - ipywidgets=8.1
  - matplotlib=3.8
  - numpy=1.26
  - pandas=2.1
  - pillow=10.0
  - scikit-learn=1.3
  - scipy=1.11
  - requests=2.31
  - tqdm=4.66
  - seaborn=0.13
  - graphviz
  - python-graphviz
  - pydot=1.4
  - pip:
    # Core packages with fixed versions for compatibility
    - keras==3.11.3
    - tensorflow==2.17.1
    - tf-keras==2.17.0
    - keras-hub==0.21.1
    # Additional packages
    - kagglehub>=0.3.0
    - tensorflow-datasets>=4.9.0
    - tensorflow-hub>=0.16.0
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - datasets>=2.14.0
